name: Rust Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: sudo apt-get install -y wireshark-dev libwireshark-dev libglib2.0-dev pkg-config
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo run --release --example basic_usage -- ./examples/http.cap --json-only
